certificates:
  example.com:
    domains:
      - example.com
      - "*.example.com"
    challenge: dns-01
    dns-01:
      # name: example.com # if the domains list only has subdomains
      email: "admin@example.com"
      key: "api-key-here"
      dane:
        - dane1
    copy:
      privkey: /etc/ssl/private/{name}.key
      fullchain: /etc/ssl/private/{name}.pem

alldone:
  - systemctl reload nginx
